# site properties and page defaults
title: trishullab
subtitle: 
description: The Trishul lab at the University of Texas at Austin studies a broad range of problems the interface of automated reasoning, machine learning, and programming languages. We hope that our solutions to these problems will lead to a new class of intelligent systems that are reliable, secure, and transparent by construction and can perform reasoning-intensive tasks beyond the scope of contemporary AI.
header: images/trishul-12-3.png
footer: images/background.jpg

# site social media and other links
links:
  email: swarat@cs.utexas.edu
#  orcid: 0000-0001-8713-9213
  google-scholar: 9j6RBYQAAAAJ
  github: trishullab
  twitter: swarat
#  youtube: trishullab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
